services:
  web-app:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./config:/config
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - CONFIG_PATH=/go/config/dev.yaml
    command: >
      sh -c "./url-compression-api"

    depends_on:
      - database

  database:
   image: postgres:14-alpine
   environment:
     - POSTGRES_DB=${DB_NAME}
     - POSTGRES_USER=${DB_USER}
     - POSTGRES_PASSWORD=${DB_PASS}
